[package]
name = "xtce-rs"
version = "0.1.0"
authors = ["Nicolae Mihalache <nicolae.mihalache@spaceapplications.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roxmltree = "0.11.0"
bimap = "0.4.0"
hex = "0.4.2"
enum-map = "0.6.2"

[dependencies.lasso]
version = "0.2.2"
features = ["multi-threaded"]
